using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Employees;
using Employees.Fakes;
 
namespace EmployeeManager.Tests
{
    [TestClass]
    public class EmployeeManagerTests
    {
        [TestMethod]
        public void EmployeeManager_GetEmployeeID_ForJim_Returns12()
        {
            // arrange
            // Create our own implementation of IEmployeeManagerHelper
            //      (one that doesn't throw an exception)
            IEmployeeManagerHelper emh =
                new Employees.Fakes.StubIEmployeeManagerHelper() // Generated by fakes
                {
                    // define each method
                    GetAnEmpString = (name) => { return 12; }
                };

            Employees.EmployeeManager sut = new Employees.EmployeeManager();

            // act
            var empID = sut.GetEmployeeIdByName("Jim", emh); // pass the stub to the method

            // assert font
            Assert.AreEqual(12, empID); 

        }
    }
}
